---
title: "DiD-methods collection document"
author: Haakon Gjerløw
date: 22.10.2022

knit: ( 
  function(input_file, encoding) {
    out_dir <- 'docs';
    
    rmarkdown::render(
    input       = input_file,
    encoding    = encoding,
    output_file = file.path(dirname(input_file), out_dir, 'index.html') ) })
---

# Overview
A number of articles have been published since 2015 on complications related to difference-in-differences (DiD) estimators with more than two units and more than two time-periods. Here we have tried to compile and understand what these complications/problems are, some possible diagnostics and solutions, and wider implications (e.g., to panel data analysis more generally).

[**Introduction**](intro.html) introduces the DiD-estimator with the most basic canonical case, and then explains how more complex scenarios breaks the logic of the estimator.

[**Problems**](problems.html) list articles that identify problems and complications with the standard TWFE and DiD-estimator, and ways to diagnose for those problems.

[**Solutions**](solutions.html) gives a summary of articles that offer solutions to the problems.

[**Definitions**](definitions.html) is a list of definitions for common concepts in the literature.


# tldr; Just give me the answer
Many of the contributions talk about and deal with the same problem(s). The main problem is that the TWFE/standard DiD-estimator _potentially_ uses previously treated units as control-group units for other treated units. This is only a problem when units receive treatment at different points in time _and_ the effect of the treatment is heterogeneous. There are both parametric regression solutions and non-parametric matching solutions to this particular issue. However, all solutions cost power.

For applied researchers, we believe that two contributions cover what you need:

**Diagnostics:** [**Goodman-Bacon 2018**](problems.html) offers solutions to identify whether there is a problem in your TWFE model. Out-of-the-box code in `R` and `Stata`.

**Solution:** [**Imai, Kim and Wang 2021**](solutions.html) offers a flexible solution which also incorporates matching for time-series cross-sectional data to establish parallel trends (balance on observable confounders). Out-of-the-box code in `R`.

# Further issues

It remains a problem that the vast majority of articles only deal with binary treatments (but see [**Callaway, Goodman–Bacon, and Sant'Anna 2021**](https://arxiv.org/abs/2107.02637)). A similar issue to treatment heterogeneity seems to occur when there are varying treatment dosages for units across time (which is often the case for observational data). E.g., a question that arises is how should treatments be homogeneous when varying treatment dosages? All studies assume that units are treated in all subsequent periods after becoming treated. Imai, Kim and Wang (2021) provides the user with an option to define when units leave treatment (effectively becoming a new observation). More than pointing to something wrong with the TWFE estimator, the studies show the complexity of panel data analysis, and the importance of really thinking through what (average) effect you want to estimate and which you really are estimating.


# Other resources

<https://asjadnaqvi.github.io/DiD/docs/02_R/>

<https://andrewcbaker.netlify.app/2019/09/25/difference-in-differences-methodology/>

<https://matheusfacure.github.io/python-causality-handbook/24-The-Diff-in-Diff-Saga.html>

<https://www.andrewheiss.com/blog/2021/08/25/twfe-diagnostics/>
